/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mibprojekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author trnfa
 */
public class BytLosen extends javax.swing.JFrame {
     private InfDB idb;
    /**
     * Creates new form bytLosen
     */
    public BytLosen(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonChangePW = new javax.swing.JButton();
        fieldNyttPWUpprepa = new javax.swing.JPasswordField();
        fieldNyttPW = new javax.swing.JPasswordField();
        fieldOldPW = new javax.swing.JPasswordField();
        txtRepeatPW = new javax.swing.JLabel();
        txtNewPW = new javax.swing.JLabel();
        txtOldPW = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonChangePW.setText("Change Password");
        buttonChangePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChangePWActionPerformed(evt);
            }
        });

        txtRepeatPW.setText("Repeat Password");

        txtNewPW.setText("Enter New Password");

        txtOldPW.setText("Enter Old Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonChangePW)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldNyttPWUpprepa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNewPW))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRepeatPW)
                    .addComponent(fieldNyttPW, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOldPW)
                    .addComponent(fieldOldPW, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(txtOldPW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldOldPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRepeatPW)
                    .addComponent(txtNewPW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNyttPWUpprepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNyttPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonChangePW, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChangePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChangePWActionPerformed

        if (Validering.textFaltHarVarde(fieldOldPW) && Validering.textFaltHarVarde(fieldNyttPW) && Validering.textFaltHarVarde(fieldNyttPWUpprepa)){
            String userOldPW = fieldOldPW.getText();
            String userNyttPW = fieldNyttPW.getText();
            String userNyttPWUpprepa = fieldNyttPWUpprepa.getText();
            
            String userID = Inlogg.getUserID(); 
            System.out.println(userID);
            String realOldPW = Inlogg.getUserLosen();
            
            if (userOldPW.equals(realOldPW)){
                if (userNyttPW.equals(userNyttPWUpprepa)){              

                    try {
                      
                        if (!Inlogg.getVal()){
                            idb.fetchSingle("UPDATE alien SET Losenord = '" + userNyttPW + "' WHERE Alien_ID = " + userID);
                            JOptionPane.showMessageDialog(null, "Password changed.");
                            new Startsida_Alien(idb).setVisible(true);
                           
                        }

                        else if (Inlogg.getVal()){
                            idb.fetchSingle("UPDATE agent SET Losenord = '" + userNyttPW + "' WHERE Agent_ID = " + userID);
                            new Startsida_Agent(idb).setVisible(true);
                        }
                        else 
                            System.out.println("something went wrong");
                    }
                    catch (Exception ettUndantag){
                        JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator.");
                        System.out.println("InternFelmeddelande:" + ettUndantag.getMessage());
                    }
                }
                else 
                    JOptionPane.showMessageDialog(null, "The two matching passwords does not match.");
            }
            else 
                JOptionPane.showMessageDialog(null, "Your entered password does not match your old password.");
            
        }
    }//GEN-LAST:event_buttonChangePWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BytLosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BytLosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BytLosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BytLosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              // new BytLosen(InfDB idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChangePW;
    private javax.swing.JPasswordField fieldNyttPW;
    private javax.swing.JPasswordField fieldNyttPWUpprepa;
    private javax.swing.JPasswordField fieldOldPW;
    private javax.swing.JLabel txtNewPW;
    private javax.swing.JLabel txtOldPW;
    private javax.swing.JLabel txtRepeatPW;
    // End of variables declaration//GEN-END:variables
}
